FROM golang:1.24-alpine

WORKDIR /app

COPY . .

RUN go test ./... && \
    CGO_ENABLED=0 GOOS=linux go build \
      -trimpath \
      -ldflags="-s -w" \
      -o service \
      .

EXPOSE 8080

CMD ["./service"]
